#!/usr/bin/env bash

###############################################################################
# Script Name:
#   install_python_packages.sh
#
# Description:
#   Install or restore Python packages using exact versions recorded in a
#   requirements-style text file generated by:
#
#       export_python_packages.sh
#
#   Example input file:
#
#       numpy==2.1.3
#       pandas==2.2.3
#       requests==2.32.3
#
#   The script uses:
#
#       python -m pip install \
#           --upgrade \
#           --force-reinstall \
#           -r python_packages.txt
#
#   Behavior:
#
#   - Package is missing:
#       -> install it.
#
#   - Installed version is older:
#       -> upgrade it to the specified version.
#
#   - Installed version is newer:
#       -> downgrade it to the specified version.
#
#   - Installed version is already correct:
#       -> reinstall it because --force-reinstall is enabled.
#
# Usage:
#
#   1. Restore packages from the default file:
#
#       ./install_python_packages.sh
#
#      Default input file:
#
#       python_packages.txt
#
#   2. Use another package file:
#
#       ./install_python_packages.sh requirements_backup.txt
#
#   3. Use a specific Python interpreter:
#
#       PYTHON_BIN=python3.11 ./install_python_packages.sh
#
#   4. Restore packages into a virtual environment:
#
#       source .venv/bin/activate
#       ./install_python_packages.sh python_packages.txt
#
# Recommended workflow:
#
#   On machine/environment A:
#
#       source .venv/bin/activate
#       ./export_python_packages.sh python_packages.txt
#
#   Copy the file and scripts to machine/environment B.
#
#   Then:
#
#       python3 -m venv .venv
#       source .venv/bin/activate
#       ./install_python_packages.sh python_packages.txt
#
# Important:
#
#   This script modifies the Python environment associated with PYTHON_BIN.
#
#   Always verify the printed Python executable before installation.
#
#   Restoring an environment works best when:
#
#       - Python major/minor versions are the same.
#       - Operating systems are compatible.
#       - CPU architectures are compatible.
#
#   Some packages contain native binaries and may not support every
#   Python/OS/architecture combination.
#
###############################################################################

set -euo pipefail


###############################################################################
# Configuration
###############################################################################

# Python executable.
#
# Override example:
#
#   PYTHON_BIN=python3.11 ./install_python_packages.sh
#
PYTHON_BIN="${PYTHON_BIN:-python}"

# Requirements/package-version file.
#
# Override example:
#
#   ./install_python_packages.sh backup_packages.txt
#
PACKAGE_FILE="${1:-python_packages.txt}"


###############################################################################
# Check Python
###############################################################################

if ! command -v "$PYTHON_BIN" >/dev/null 2>&1; then
    echo "ERROR: Python executable not found: $PYTHON_BIN" >&2
    exit 1
fi


###############################################################################
# Check pip
###############################################################################

if ! "$PYTHON_BIN" -m pip --version >/dev/null 2>&1; then
    echo "ERROR: pip is not available for: $PYTHON_BIN" >&2
    exit 1
fi


###############################################################################
# Check package file
###############################################################################

if [[ ! -f "$PACKAGE_FILE" ]]; then
    echo "ERROR: Package file does not exist:" >&2
    echo "       $PACKAGE_FILE" >&2
    exit 1
fi

if [[ ! -s "$PACKAGE_FILE" ]]; then
    echo "ERROR: Package file is empty:" >&2
    echo "       $PACKAGE_FILE" >&2
    exit 1
fi


###############################################################################
# Display environment information
###############################################################################

PYTHON_PATH="$("$PYTHON_BIN" -c 'import sys; print(sys.executable)')"
PYTHON_VERSION="$("$PYTHON_BIN" --version 2>&1)"
PIP_VERSION="$("$PYTHON_BIN" -m pip --version)"

PACKAGE_COUNT="$(grep -c '==' "$PACKAGE_FILE" || true)"

echo "============================================================"
echo " Restore Python Packages"
echo "============================================================"
echo
echo "Python executable : $PYTHON_PATH"
echo "Python version    : $PYTHON_VERSION"
echo "pip              : $PIP_VERSION"
echo "Package file     : $PACKAGE_FILE"
echo "Packages         : $PACKAGE_COUNT"
echo


###############################################################################
# Show packages before installation
###############################################################################

echo "Package file preview:"
echo "------------------------------------------------------------"
head -n 10 "$PACKAGE_FILE"
echo "------------------------------------------------------------"
echo


###############################################################################
# Install exact package versions
###############################################################################

echo "Installing/restoring Python packages..."
echo

# --upgrade
#     Allows pip to change an already-installed package version.
#
# --force-reinstall
#     Reinstalls packages even when the requested version is already installed.
#
# -r
#     Reads package/version requirements from the specified file.
#
"$PYTHON_BIN" -m pip install \
    --upgrade \
    --force-reinstall \
    -r "$PACKAGE_FILE"


###############################################################################
# Verify installed packages
###############################################################################

echo
echo "============================================================"
echo " Installation completed"
echo "============================================================"
echo

echo "Checking dependency consistency..."

# "pip check" verifies whether installed packages have compatible dependencies.
#
# Example problem:
#
#   package-A requires package-B>=2.0, but package-B 1.5 is installed.
#
if "$PYTHON_BIN" -m pip check; then
    echo
    echo "Dependency check passed."
else
    echo
    echo "WARNING: pip detected dependency conflicts." >&2
    echo "Review the messages above." >&2
fi


###############################################################################
# Final information
###############################################################################

echo
echo "Installed package versions:"
echo "------------------------------------------------------------"

"$PYTHON_BIN" -m pip list --format=freeze

echo "------------------------------------------------------------"
echo
echo "Restore process finished."